### ISSUE TITLE
Issue at first connection using config flow

### ISSUE THREAD

**Issue by elkarto** [benlbrm/ha-hottoh-component#1]
First of all, thank you very much for developing the component. 

There are many stoves using this system (mine is Edilkamin) and being able to integrate them in home assistant is a big step forward.

I have a problem when adding the integration. I think it is related to hottohpy.  

The first time I try to add the stove, I get the error "Unexpected exception". 

In the home assistant log it says the following:

```
2021-11-19 13:21:50 ERROR (MainThread) [custom_components.hottoh.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/hottoh/config_flow.py", line 87, in async_step_user
info = await validate_input(self.hass, user_input)
File "/config/custom_components/hottoh/config_flow.py", line 39, in validate_input
info = await async_connect_or_timeout(hass, hottoh)
File "/config/custom_components/hottoh/__init__.py", line 247, in async_connect_or_timeout
name = hottoh.get_name()
File "/usr/local/lib/python3.9/site-packages/hottohpy/hottoh.py", line 256, in get_name
if self.get_manufacturer() is None:
File "/usr/local/lib/python3.9/site-packages/hottohpy/hottoh.py", line 267, in get_manufacturer
return self._getManufacturer()
File "/usr/local/lib/python3.9/site-packages/hottohpy/hottoh.py", line 290, in _getManufacturer
return str(self._data[StoveRegisters.INDEX_MANUFACTURER])
AttributeError: 'Hottoh' object has no attribute '_data'
```

If I try to add it again, the error becomes "Failed to connect", and the log shows this:

```
2021-11-19 13:22:45 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 106] Socket is connected
2021-11-19 13:22:45 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 106] Socket is connected
2021-11-19 13:22:45 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 106] Socket is connected
2021-11-19 13:22:45 ERROR (hottohpy) [hottohpy.client] Unable to connect to 192.168.5.90
2021-11-19 13:22:45 WARNING (hottohpy) [hottohpy.hottoh] Unexpectedly disconnected from Hottoh 192.168.5.90, code Unable to connect to Hottoh at 192.168.5.90
```

I think that due to the first error, the socket is somehow left open, and it cannot be reopened.

I have seen that you have uploaded a new version of hottohpy (0.0.17), I have tried updating the dependencies to this version, but the problem persists.

**Comment by benlbrm** [comment]
Hello,
there is two issues here:
-1- your first error should be corrected with hottohpy version 0.0.18, I corrected the error.
-2- for the second, I know I still have some problem when the integration is created at first, HA needs to reboot, I need to work on that.

Since this is my first integration and also my first python experience, I will try to do my best ;-)

**Comment by benlbrm** [comment]
I've just push new hottohpy version with improvements for the config flow (0.0.21)
and also pushed new version of the integration.

I would also be interested by the vendor value of your stove, to add the builder name:
![image](https://user-images.githubusercontent.com/16845043/142695109-5ba22157-7b2e-44a3-aff7-005124e38aee.png)

**Comment by elkarto** [comment]
Wow! That's fast!!
It may be your first integration, but it's certainly a very useful integration and one that I'm sure many people will appreciate.


I have just tested the new version. I will try to describe It's whole behavior.

First of all, after starting home assistant (even before configuring the integration) I got this error:

```
2021-11-20 00:31:45 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/hottoh/config_flow.py", line 70, in async_step_dhcp
info = await validate_input(self.hass, [host, HOTTOH_DEFAULT_PORT])
File "/config/custom_components/hottoh/config_flow.py", line 38, in validate_input
address=data[CONF_HOST],
TypeError: list indices must be integers or slices, not str
```

I had already seen this error with the previous version. I have also seen something similar trying to run hottohpy on my desktop PC.

Despite the error, I have tried to configure the integration.

The first time I did it, it added "stove 85" to the list of integrations. However, a red error appeared indicating that the integration could not load. It also did not add any devices or entities.

I checked the logs and saw this:


```
2021-11-20 00:37:47 ERROR (hottohpy) [hottohpy.client] Socket already connected to 192.168.5.90
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:47 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor

...... More than 600 entries redacted .......

2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Stove 85' for hottoh integration not ready yet; Retrying in background
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
2021-11-20 00:37:57 ERROR (hottohpy-client) [hottohpy.client] Connection Error : [Errno 9] Bad file descriptor
```

After seeing the flood, I deleted "Stove 85". The flood has stopped.


Then I have tried adding the integration again. This time, the error message "Failed to connect" appears, the config form is not closed and no "Stove 85" was added. The log show:

```
2021-11-20 00:49:22 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 9] Bad file descriptor
2021-11-20 00:49:22 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 9] Bad file descriptor
2021-11-20 00:49:22 ERROR (hottohpy) [hottohpy.client] Can't connect to 192.168.5.90, error: [Errno 9] Bad file descriptor
2021-11-20 00:49:22 ERROR (hottohpy) [hottohpy.client] Unable to connect to 192.168.5.90
2021-11-20 00:49:22 WARNING (hottohpy) [hottohpy.hottoh] Unexpectedly disconnected from Hottoh 192.168.5.90, code Unable to connect to Hottoh at 192.168.5.90
```

These lines appears each time I try to add the stove, but only 5 lines each time, not flooding.



I hope I have explained it well enough.

Thank you very much for your quick response, if I can help you in any way do not hesitate to ask me.

**Comment by elkarto** [comment]
Interesting.

After restarting Home Assistant again, I have managed to add the stove successfully.

Here is the "manufacturer" that appears:

![image](https://user-images.githubusercontent.com/36958524/142707641-1a8ad777-3d96-4932-b21c-9d9c629b0a0d.png)

**Comment by elkarto** [comment]
Well, there still seems to be a problem:

![image](https://user-images.githubusercontent.com/36958524/142708074-f6bed02b-4b15-42fc-bc22-fa279c304fb3.png)

This message appears 40.000 times in ten minutes.

**Comment by benlbrm** [comment]
Ok...
There were two problem,
first, I have try to enable discovery form dhcp to automatically add Hottoh integration to HA, but on my side it didn't detect it so I have not been able to test it correctly -> It have been removed from now
second, it should be better in version 0.0.22 of hottohpy and version 0.04 of this integration.
You will still have an error just after adding the integration, but after few seconds, the climate and sensors will arrive. This is because the stove did not accept more than one simultaneous connection.
Can you tell me if it's better ?
I'm also actually thinking of removing the config_flow and go back to configuration.yaml because, I have added three preset (away, eco and comfort) and there is no way to reconfigure them without going trough configuration.yaml
Going back to configuration.yaml will also really simply the code for all the error you got ;-)

**Comment by elkarto** [comment]
You are quicker at fixing problems than I am at testing them. Hahah

I can confirm that it now works perfectly.

As you pointed out, it gave connection errors just after adding the integration. But after that everything works fine.

I see that it exposes much less data than can be seen/controlled in jeedom. But this is version 0.0.22, and just being able to turn the stove on and off from home assistant is a huge step forward. You are on the right track.

No doubt there is work ahead, my python knowledge is quite basic but I'll be happy to help you in any way I can. As for example in the translation of the strings to spanish.

In my opinion, I think the config flow is very convenient for certain types of integrations. However, I believe that for this particular one, the .yaml configuration is perfectly valid. People are not adding stoves to their homes every day.

So, if this simplifies the code and avoids potential problems, I think going back to .yaml is a good option.


Thank you again for your work.

**Comment by benlbrm** [comment]
Ok cool thanks for your feedback !
There is other data points than I can output from the integration
![image](https://user-images.githubusercontent.com/16845043/142929839-b8e98916-6631-4948-8411-a7878a835b11.png)
but I know, my stove did not support all of them and I'm not sur to have all possible.

**Comment by elkarto** [comment]
Mine is a water stove, and the application allows these parameters to be displayed/controlled:

- In the main screen:

![image](https://user-images.githubusercontent.com/36958524/142934664-b4f5ed0d-d702-433f-aa7c-237e7c25d959.png)

- [ ] In the upper left corner there is an icon indicating whether the water pump is running or not.

- [X] In the middle there is an icon indicating the current status. This is already exposed, however, I have seen the following:  

  When the pellets are running out, the cooker makes a beep. However, neither the app icon nor the home assistant "action" entity change, it is kept on "heating".
  If the stove is switched off due to lack of pellets, then yes, the entity "action" changes to "stopping" and then to "end pellet".
  I don't know if it would be possible  to read an extra status indicating "low pellet". But it would be a very useful feature, to be able to notify about the lack of pellets via home assistant.


- [X] Below the icon, it shows the current environment temperature, which is already exposed.

- [ ] Finally, the water temperature is displayed. I guess it corresponds to the index #17 of your screenshot. 


- In the status screen:

![image](https://user-images.githubusercontent.com/36958524/142936491-e392956a-e917-4f84-be8e-77bd89455ef8.png)


- [ ] Firstly, the power at which the stove is operating. Guess it is parameter #22.

- [X] Set and Environment, already exposed.

- [ ] Water temperature, the same as shown in the main screen.

- [X] Fumes temperature, already exposed.

- [X] Fumes fan speed, already exposed. As you see in the snapshot, the unit seems to be g/m and not rpm. But not sure if this is correct in the app.

- [ ] Last one, air exchanger fan speed. This is not exposed and I think it must be #27, #30 or #33.


- In the control screen:

![image](https://user-images.githubusercontent.com/36958524/142937735-124efa92-4e1f-43b3-b501-34592c4dff84.png)

- [X] Firstly, the Eco mode, already exposed. I really don't know if it has any real effect on my stove.

- [ ] Next, the Chrono mode, not exposed. For me it is secondary, because thanks to the integration, it will be possible to schedule the stove using home assistant.
- [ ] Next, the programmed power. I don't know how it behaves because the stove adjusts this value automatically according to the temperatures. It's not exposed but I guess it is #23.
- [X] Next, the environment setpoint. Already exposed.

- [ ] Last, and very important In my opinion, the air exchanger fan speed. I can change it from 0 - 5 and "Auto".  I suppose it will be #28, #31 or #34.



As you can see, the app does not let you adjust the water temperature setpoint. But, according to your screenshots, I think it is possible to adjust it using parameter #18. This would be very very useful in my opinion, especially because it is not possible from the app.

I'm sorry for rambling, It is not my intention to give you so much work, only that you know which parameters are interesting in the case of water stoves.

Feel free to move this to a new issue or enhancement (or six, or seven ;) ). This is probably not the best place to discuss it.
